version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli --upgrade --user

      - run:
          name: deploy
          command: |
            . venv/bin/activate
            ./deploy.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies
